#! /bin/bash

for type in 1 2 3
  do
  for bandwidth in 1 1.5 2 2.5 3
  do
#    for graph in grid_2d erdos_renyi hypercube balanced_tree small_world
#    do
#      for stepsize in 100 #50 500
#      do
#        sbatch ../script.sh PrimalDual.py Prob --graph_type $graph --bandwidth_coefficient $bandwidth --stepsize $stepsize --bandwidth_type $type
#      done
#    done
    for graph in real1 real2 #abilene2 geant dtelekom example1 example2 abilene abilene1
    do
      for stepsize in 100 #10 50
      do
        sbatch ../script.sh PrimalDual.py Prob --graph_type $graph --bandwidth_coefficient $bandwidth --stepsize $stepsize --query_nodes 4 --bandwidth_type $type
      done
    done
  done
done
