#! /bin/bash

sbatch ../script.sh plotter.py --graph_type grid_2d --graph_size 20 --catalog_size 10 --demand_size 100 --query_nodes 2  --bandwidth_coefficient 0.7 --stepsize 10

sbatch ../script.sh plotter.py --graph_type grid_2d --graph_size 20 --catalog_size 10 --demand_size 100 --query_nodes 2  --bandwidth_coefficient 0.7 --stepsize 50

sbatch ../script.sh plotter.py --graph_type grid_2d --graph_size 20 --catalog_size 10 --demand_size 100 --query_nodes 2  --bandwidth_coefficient 0.75 --stepsize 10

sbatch ../script.sh plotter.py --graph_type grid_2d --graph_size 20 --catalog_size 10 --demand_size 100 --query_nodes 2  --bandwidth_coefficient 0.75 --stepsize 50

sbatch ../script.sh plotter.py --graph_type grid_2d --graph_size 20 --catalog_size 10 --demand_size 100 --query_nodes 2  --bandwidth_coefficient 0.8 --stepsize 10