#! /bin/bash

for bandwidth in 1 1.5
do
    for graph in grid_2d erdos_renyi hypercube star
    do
        sbatch ../script.sh ProbGenerate.py Prob --graph_type $graph --bandwidth_coefficient $bandwidth
    done
done

#    geant abilene dtelekom